[package]
description = "Tanour"
name = "tanour"
version = "0.1.0"
authors = ["mantre <mantre@protonmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
primitive-types = "0.7.2"
log = "0.4"
wasmi = "0.7.0"
parity-wasm = "0.41.0"
snafu = "0.6.9"
keccak-hash = "0.5.1"
pwasm-utils = "0.16.0"

[dev-dependencies]
hex = "0.4.2"
simple_logger = "1.4.0"


[lib]
path = "src/lib.rs"
