on: [pull_request]
name: Formatting

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: fmt check
      run: cargo fmt --all -- --check

    - name: Clippy check
      run: cargo clippy --all-targets --all-features -- -D warnings