on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Testing

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unit tests
      run: cargo test
